package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/photo-pixels/gateway/internal/graph/model"
	api "github.com/photo-pixels/gateway/pkg/gen/user_account"
)

// Status is the resolver for the status field.
func (r *userProfileResolver) Status(ctx context.Context, obj *api.GetUserResponse) (model.AuthStatus, error) {
	if obj == nil {
		return model.AuthStatusAuthStatusUnknown, nil
	}
	return model.AuthStatus(obj.Status.String()), nil
}

// UserProfile returns UserProfileResolver implementation.
func (r *Resolver) UserProfile() UserProfileResolver { return &userProfileResolver{r} }

type userProfileResolver struct{ *Resolver }
